# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject_registered',
            field=models.BooleanField(default=False),
        ),
    ]
