# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject1',
            field=models.CharField(choices=[('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='subject2',
            field=models.CharField(choices=[('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='subject3',
            field=models.CharField(choices=[('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100),
        ),
    ]
