# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170906_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=100)),
                ('BankBranch', models.CharField(max_length=100)),
                ('AccountNo', models.CharField(max_length=100)),
                ('IFSCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMail', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('PermAddress', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='text',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='Roll',
        ),
    ]
