# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20170906_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Semester', models.IntegerField(default=0)),
                ('subject1', models.CharField(choices=[('none', 'None'), ('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100)),
                ('subject2', models.CharField(choices=[('none', 'None'), ('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100)),
                ('subject3', models.CharField(choices=[('none', 'None'), ('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='subject1',
            field=models.CharField(choices=[('none', 'None'), ('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject2',
            field=models.CharField(choices=[('none', 'None'), ('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject3',
            field=models.CharField(choices=[('none', 'None'), ('ma202', 'MA202: Statistics and Probability'), ('cso211', 'CSO211: Computer System Organization'), ('cso204', 'CSO204: Discrete Maths'), ('me104', 'ME104: Engineering Mechanics'), ('h105', 'H105: Philosophy')], default='', max_length=100),
        ),
    ]
