# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170907_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.CharField(max_length=100)),
                ('PermAddress', models.CharField(max_length=100)),
                ('Parents_income', models.IntegerField(default=0)),
            ],
        ),
    ]
