# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_scholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Bank'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='AccountNo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='BankBranch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='BankName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='IFSCode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
