# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0011_bank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Personal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Summer',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summer',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
