# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20170910_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subject_registered',
        ),
        migrations.AddField(
            model_name='bank',
            name='Roll',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='Roll',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
