# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20170929_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject1',
            field=models.CharField(choices=[('none', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject2',
            field=models.CharField(choices=[('none', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject3',
            field=models.CharField(choices=[('none', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summer',
            name='subject1',
            field=models.CharField(choices=[('none', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summer',
            name='subject2',
            field=models.CharField(choices=[('none', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summer',
            name='subject3',
            field=models.CharField(choices=[('none', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy')], default='', max_length=100),
        ),
    ]
