# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_subject_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Summer',
        ),
    ]
