# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20171001_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
