# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
