# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_posts_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('idd', 'idd'), ('phd', 'phd')], default='', max_length=100)),
                ('department', models.CharField(choices=[('Ceramic Engineering', 'Ceramic Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Pharmaceutical Engineering', 'Pharmaceutical Engineering'), ('Material Science and Technology', 'Material Science and Technology'), ('Biochemical Engineering', 'Biochemical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Department of Chemistry', 'Department of Chemistry'), ('Department of Physics', 'Department of Physics'), ('Department of Mathematical Sciences', 'Department of Mathematical Sciences')], default='', max_length=100)),
                ('year', models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V')], default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='Roll',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Roll',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='EMail',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Roll',
        ),
        migrations.AddField(
            model_name='course',
            name='subject4',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='subject5',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Batch'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portal.Batch'),
        ),
    ]
