# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20171028_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(default='', max_length=300),
        ),
    ]
