# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20171028_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='batch',
        ),
        migrations.AddField(
            model_name='posts',
            name='department',
            field=models.CharField(choices=[('Ceramic Engineering', 'Ceramic Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Pharmaceutical Engineering', 'Pharmaceutical Engineering'), ('Material Science and Technology', 'Material Science and Technology'), ('Biochemical Engineering', 'Biochemical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Department of Chemistry', 'Department of Chemistry'), ('Department of Physics', 'Department of Physics'), ('Department of Mathematical Sciences', 'Department of Mathematical Sciences')], default='Ceramic Engineering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='program',
            field=models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('idd', 'idd'), ('phd', 'phd')], default='btech', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='year',
            field=models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V')], default='First', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('Ceramic Engineering', 'Ceramic Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Pharmaceutical Engineering', 'Pharmaceutical Engineering'), ('Material Science and Technology', 'Material Science and Technology'), ('Biochemical Engineering', 'Biochemical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Department of Chemistry', 'Department of Chemistry'), ('Department of Physics', 'Department of Physics'), ('Department of Mathematical Sciences', 'Department of Mathematical Sciences')], default='Ceramic Engineering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('idd', 'idd'), ('phd', 'phd')], default='btech', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V')], default='First', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Ceramic Engineering', 'Ceramic Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Pharmaceutical Engineering', 'Pharmaceutical Engineering'), ('Material Science and Technology', 'Material Science and Technology'), ('Biochemical Engineering', 'Biochemical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Department of Chemistry', 'Department of Chemistry'), ('Department of Physics', 'Department of Physics'), ('Department of Mathematical Sciences', 'Department of Mathematical Sciences')], default='Ceramic Engineering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('idd', 'idd'), ('phd', 'phd')], default='btech', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V')], default='First', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=100),
        ),
    ]
