# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20171028_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='program',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('idd', 'IDD'), ('phd', 'PHD')], default='btech', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('idd', 'IDD'), ('phd', 'PHD')], default='btech', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('idd', 'IDD'), ('phd', 'PHD')], default='', max_length=100, null=True),
        ),
    ]
