# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20171028_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('IDD', 'IDD'), ('PHD', 'PHD')], default='B.Tech', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='I', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('IDD', 'IDD'), ('PHD', 'PHD')], default='B.Tech', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='I', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('IDD', 'IDD'), ('PHD', 'PHD')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='I', max_length=50, null=True),
        ),
    ]
