# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_teacherpersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('present', models.ManyToManyField(to='portal.UserProfile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subject')),
            ],
        ),
    ]
