# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20171029_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.ManyToManyField(null=True, to='portal.UserProfile'),
        ),
    ]
