# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20171029_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatType',
            field=models.CharField(choices=[('Department', 'Department'), ('Class', 'Class')], default='Class', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='department',
            field=models.CharField(choices=[('Ceramic Engineering', 'Ceramic Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Pharmaceutical Engineering', 'Pharmaceutical Engineering'), ('Material Science and Technology', 'Material Science and Technology'), ('Biochemical Engineering', 'Biochemical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Department of Chemistry', 'Department of Chemistry'), ('Department of Physics', 'Department of Physics'), ('Department of Mathematical Sciences', 'Department of Mathematical Sciences')], default='Ceramic Engineering', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='chat',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='I', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacherpersonal',
            name='adminPos',
            field=models.CharField(choices=[('None', 'None'), ('Director', 'Director'), ('Dean of Academic Affairs', 'Dean of Academic Affairs'), ('Associate Dean of Academic Affairs', 'Associate Dean of Academic Affairs'), ('Dean of Student Affairs', 'Dean of Student Affairs'), ('Dean of Resource and Alumni', 'Dean of Resource and Alumni'), ('Dean of Research and Development', 'Dean of Research and Development'), ('Registrar', 'Registrar'), ('Professor Incharge(Faculty Affairs)', 'Professor Incharge(Faculty Affairs)')], default='Ceramic Engineering', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherpersonal',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default='B.Tech', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherpersonal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
