# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_auto_20171030_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='PermAddress',
            field=models.CharField(max_length=100, verbose_name=b'Permanent Address'),
        ),
    ]
