# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_auto_20171031_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='AccountNo',
            field=models.CharField(default='', max_length=100, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='BankBranch',
            field=models.CharField(default='', max_length=100, verbose_name='Bank Branch'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='BankName',
            field=models.CharField(default='', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject1',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100, verbose_name='Subject 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject2',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100, verbose_name='Subject 2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject3',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100, verbose_name='Subject 3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject4',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100, verbose_name='Subject 4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject5',
            field=models.CharField(choices=[('None', 'None'), ('MA202: Statistics and Probability', 'MA202: Statistics and Probability'), ('CSO211: Computer System Organization', 'CSO211: Computer System Organization'), ('CSO204: Discrete Maths', 'CSO204: Discrete Maths'), ('ME104: Engineering Mechanics', 'ME104: Engineering Mechanics'), ('H105: Philosophy', 'H105: Philosophy'), ('MA101: Engineering Mathematics-I', 'MA101: Engineering Mathematics-I'), ('MA102: Engineering Mathematics-II', 'MA102: Engineering Mathematics-II'), ('CSO101: Introduction to Computer Programming', 'CSO101: Introduction to Computer Programming'), ('CSO102: Data Structures', 'CSO102: Data Structures'), ('EO101: Fundamentals of Electrical Engineering', 'EO101: Fundamentals of Electrical Engineering'), ('PHY101: Physics - Classical, Quantum and Relativistic', 'PHY101: Physics - Classical, Quantum and Relativistic'), ('PHY102: Physics - Electrodynamics', 'PHY102: Physics - Electrodynamics'), ('CY101: Chemistry', 'CY101: Chemistry'), ('CSE105: Information Technology Workshop-I', 'CSE105: Information Technology Workshop-I'), ('CSE205: Information Technology Workshop-II', 'CSE205: Information Technology Workshop-II'), ('H104: History and Civilization', 'H104: History and Civilization'), ('H103: Education and Self', 'H103: Education and Self'), ('H102: Development of Societies', 'H102: Development of Societies'), ('H101: Universal Human Values', 'H101: Universal Human Values')], default='None', max_length=100, verbose_name='Subject 5'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='PermAddress',
            field=models.CharField(max_length=100, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='teacherpersonal',
            name='adminPos',
            field=models.CharField(choices=[('None', 'None'), ('Director', 'Director'), ('Dean of Academic Affairs', 'Dean of Academic Affairs'), ('Associate Dean of Academic Affairs', 'Associate Dean of Academic Affairs'), ('Dean of Student Affairs', 'Dean of Student Affairs'), ('Dean of Resource and Alumni', 'Dean of Resource and Alumni'), ('Dean of Research and Development', 'Dean of Research and Development'), ('Registrar', 'Registrar'), ('Professor Incharge(Faculty Affairs)', 'Professor Incharge(Faculty Affairs)')], default='Ceramic Engineering', max_length=100, null=True, verbose_name='Administrative Position'),
        ),
        migrations.AlterField(
            model_name='teacherpersonal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='teacherpersonal',
            name='interest',
            field=models.CharField(max_length=200, verbose_name='Area(s) of Interest'),
        ),
    ]
