# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_auto_20171031_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='file',
        ),
    ]
