# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_remove_rssfeed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='date',
            field=models.DateField(),
        ),
    ]
